### PR TITLE
I am interested in using your game on my website. Could you add a license file like the MIT one in this pull request so I know how you want your software used?

### PR DESCRIPTION
**Pull request by jpbida**

### CODE REVIEW

**Comment by forax99** [comment]
Thank you for asking my game.

**Comment by jpbida** [comment]
Thanks!

**Comment by forax99** [comment]
Let me know your website.


2017. 2. 5. 오후 3:16에 "Jp Bida" <notifications@github.com>님이 작성:

**Comment by jpbida** [comment]
I'll send a pull request with a link if we end up using your code.

**Pull request merged**
